language: cpp

branches:
  only:
  - master

sudo: false
dist: trusty

cache:
  directories:
  - $HOME/deps

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Install a C++17 compliant compiler and and make it the preferred compiler
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

matrix:
  include:
    - os: linux
    - os: osx

script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
     
notifications:
  recipients:
  - faouellet@gmail.com
  email:
    on_success: change
    on_failure: always