language: cpp

branches:
  only:
  - master

sudo: false
dist: trusty

cache:
  directories:
  - $HOME/deps

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
      env: COMPILER=g++-7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-5.0
          packages:
          - clang-5.0
      env: COMPILER=clangg++-5

script: 
  - mkdir build
  - cd build
  - cmake CXX=$COMPILER ..
  - make
     
notifications:
  recipients:
  - faouellet@gmail.com
  email:
    on_success: change
    on_failure: always