version: 0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - travis

image: Visual Studio 2017

build_script:
- cmd: >-
    mkdir cmake-build

    cd cmake-build

    cmake .. -DCMAKE_CXX_FLAGS="/std:c++latest"

    cmake --build . --config Release

test: off

deploy: off